language: node_js
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="4.0"
  - TRAVIS_NODE_VERSION="4.1"
  - TRAVIS_NODE_VERSION="4.2"
  - TRAVIS_NODE_VERSION="5"
  - TRAVIS_NODE_VERSION="0.10" ARCH="x86"
  - TRAVIS_NODE_VERSION="0.12" ARCH="x86"
  - TRAVIS_NODE_VERSION="4.0" ARCH="x86"
  - TRAVIS_NODE_VERSION="4.1" ARCH="x86"
  - TRAVIS_NODE_VERSION="4.2" ARCH="x86"
  - TRAVIS_NODE_VERSION="5" ARCH="x86"
  global:
  - secure: nFQKlcfG1rV/kQm1EJtgQyRefZb6scdn/9epEaJgAyaqDRXHSZIFSuoOh4d/P5GC6V0yi6dA8I+XJsoRy29qG+JXWxN2enwjp16IbpUri9Z5H8uZPur1N6QPby9BX+PX5/4HU+KRgWtFDdfqqzbLmObXsxIUGtZtBbRY9otiUt8=
  exclude:
  - os: osx
    env: TRAVIS_NODE_VERSION="0.10" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="0.12" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="4" ARCH="x86"

node_js:
  - '0.10'
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - '5.0'
matrix:
  allow_failures:
    - node_js: '5.0'
before_install:
  - "mkdir -p ~/.npm"
before_script:
  - npm install -g grunt-cli istanbul codeclimate-test-reporter
script:
  - grunt lint
  - istanbul cover ./node_modules/.bin/_mocha spec/helper.js spec/lib/*.js spec/lib/**/*.js --report lcovonly -- -R spec
  - CODECLIMATE_REPO_TOKEN=88ec807c5d22e853e1a21b9289233f525e793f09e5e81322899ee519587d3689 codeclimate-test-reporter < coverage/lcov.info
